name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install -r requirements.txt
      - name: Running tests
        run: python3 -m unittest -v __tests__/test_*.py


  publish:
    runs-on: ubuntu-latest

    if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip setuptools wheel
            pip3 install -r requirements.txt
      - name: Building
        run: python3 setup.py sdist bdist_wheel
      - name: Publishing
        run: "python3 -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u __token__ -p '${{ secrets.PYPI_TOKEN }}'"
  