name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: python:alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running tests
        run: python3 -m unittest -v __tests__/test_*.py


  publish:
    runs-on: python:alpine

    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt

      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
